"""empty message

Revision ID: 7d922b46a6dd
Revises: 
Create Date: 2023-06-09 16:36:07.508437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d922b46a6dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_value')
    )
    op.create_table('dam_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sales_volume', sa.Float(), nullable=True),
    sa.Column('purchase_volume', sa.Float(), nullable=True),
    sa.Column('declared_sales_volume', sa.Float(), nullable=True),
    sa.Column('declared_purchase_volume', sa.Float(), nullable=True),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dam_result')
    op.drop_table('date')
    # ### end Alembic commands ###
